### ISSUE TITLE
ApiKey 格式只能是"sk-"开头

### ISSUE THREAD

**Issue by N78Wy** [jkhcc11/AISubtitle#10]
![image](https://github.com/jkhcc11/AISubtitle/assets/98439218/57be2766-53ca-407e-a752-7d9f47495bdf)
竟然已经支持了自定义代理，建议把ApiKey这里的限制也修改下，或者去掉，因为有部分代理是用自己的key，不一定是sk-开头，会导致ApiKey没有正确放入请求头里

**Comment by jkhcc11** [comment]
你提交一个pull吧  哈哈哈

**Comment by jkhcc11** [comment]
已合并
