### ISSUE TITLE
只有 5 行的字幕单页翻译提示：翻译失败翻译异常，【当前内容太多，请调整分页大小】

### ISSUE THREAD

**Issue by vicar5235** [jkhcc11/AISubtitle#13]
如题
分页已经拉到最小，单页测试翻译依旧提示：翻译失败翻译异常，【当前内容太多，请调整分页大小】
使用站点：https://ai-srt.gpt-666.com/
使用站点2：本地环境
问题依旧

**Comment by vicar5235** [comment]
![image](https://github.com/jkhcc11/AISubtitle/assets/35890470/a7436d35-3c23-43b0-b7b9-ea47a0bb2fae)

**Comment by vicar5235** [comment]
经过测试，发现是模型选择 3.5 才会出现的问题，必须选择 3.516K 才能正常翻译，而且翻译完成后的结果如果快速翻页，网页会崩溃，只能刷新恢复，但刷新后翻译的字幕就全没有了，希望能修复，谢谢作者

![image](https://github.com/jkhcc11/AISubtitle/assets/35890470/d3c2c4f1-263b-47b5-9d3b-3abd00e18368)

**Comment by jkhcc11** [comment]
你的整个字幕文件是不是很大？

**Comment by jkhcc11** [comment]
@vicar5235
