### ISSUE TITLE
我想使用GPT-4来做这件事

### ISSUE THREAD

**Issue by chonchichon** [jkhcc11/AISubtitle#14]
你好，我想使用GPT-4来做这件事，但是高转速的使用限制了我自动化这个过程。有没有什么办法可以降低转速，以便使用GPT-4？

**Comment by jkhcc11** [comment]
![image](https://github.com/jkhcc11/AISubtitle/assets/28553032/db0be67a-1414-41ea-9b02-192b2ab6eeb1)
在这里设置延迟即可，这样低转速账号也可以
